name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          pip install pytest
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest -v

  deploy:

    needs: build-test

    runs-on: ubuntu-latest

    steps:

      - name: Wait
        run: sleep 10

      - name: Deploy
        run: |
          echo "Deploying..."
          echo "Deployment Complete"

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions Deployment Success
          to: yourmail@gmail.com
          from: GitHub Actions
          body: |
            Deployment completed successfully.